#! /bin/bash

set -e

PHONE_ADB_SERIAL_NUMBER=810972cf

check_phone_is_connected() {
    if ! adb devices | grep --silent "$PHONE_ADB_SERIAL_NUMBER"; then
        echo "ERROR: phone is not connected"
        exit 1
    fi
}

check_phone_is_in_fastboot_mode() {
    fastboot devices | grep --silent "$PHONE_ADB_SERIAL_NUMBER"
}

get_lineage_version() {
    adb -s "$PHONE_ADB_SERIAL_NUMBER" shell getprop ro.lineage.version | tr -d '\n'
}

get_device_name() {
    adb -s "$PHONE_ADB_SERIAL_NUMBER" shell getprop ro.lineage.device | tr -d '\n'
}

get_device_downloads_page() {
    echo "https://download.lineageos.org/$(get_device_name)"
}

get_build_url() {
    curl --no-progress-meter "$(get_device_downloads_page)" |
        grep --perl-regexp --only-matching --ignore-case \
            "(?<=href=\")https://mirrorbits.lineageos.org/.*?$(get_lineage_version)-signed.zip(?=\")"
}

download_latest_lineageos_build() {
    # The --location lets curl follow the redirection.
    curl --location "$(get_build_url)" --output /tmp/lineageos.zip
}

extract_boot_image() {
    # See https://wiki.lineageos.org/extracting_blobs_from_zips to understand the different ways to extract the boot.img file.
    if is_ota_block_based; then
        extract_boot_image_from_block_based_ota
    elif is_ota_payload_based; then
        extract_boot_image_from_payload_based_ota
    else
        extract_boot_image_from_file_based_ota
    fi
}

extract_boot_image_from_file_based_ota() {
    echo 'ERROR: the function "extract_boot_image_from_file_based_ota" is not implemented'
    exit 1
}

install_python_protobuf() {
    sudo python3 -m pip install protobuf
}

extract_payload_from_payload_based_ota() {
    unzip -od /tmp /tmp/lineageos.zip payload.bin
}

generate_random_alnum_string_of_length_6() {
    tr -dc A-Za-z0-9 </dev/urandom | head -c 6
}

extract_boot_image_from_payload_file() {
    install_python_protobuf
    # For cases in which the repo has already been cloned, I prefer to create a random directory name to clone into, instead of deleting any file or directory on the user's machine.
    scripts_directory_name="scripts_$(generate_random_alnum_string_of_length_6)"
    git clone https://github.com/LineageOS/scripts /tmp/$scripts_directory_name
    python /tmp/$scripts_directory_name/update-payload-extractor/extract.py --partitions boot --output_dir /tmp/ /tmp/payload.bin
}

extract_boot_image_from_payload_based_ota() {
    extract_payload_from_payload_based_ota
    extract_boot_image_from_payload_file
}

is_ota_payload_based() {
    unzip -l /tmp/lineageos.zip | grep -wq payload.bin
}

is_ota_block_based() {
    unzip -l /tmp/lineageos.zip | grep -wq boot.img
}

extract_boot_image_from_block_based_ota() {
    unzip -od /tmp /tmp/lineageos.zip boot.img
}

transfer_unpatched_boot_image_to_phone() {
    adb -s "$PHONE_ADB_SERIAL_NUMBER" push /tmp/boot.img /sdcard/Download/boot.img
}

patch_boot_image_on_phone() {
    adb -s "$PHONE_ADB_SERIAL_NUMBER" shell /data/adb/magisk/boot_patch.sh /sdcard/Download/boot.img
    adb -s "$PHONE_ADB_SERIAL_NUMBER" shell mv /data/adb/magisk/new-boot.img /sdcard/Download/patched-boot.img
}

transfer_patched_boot_image_to_pc() {
    adb -s "$PHONE_ADB_SERIAL_NUMBER" pull /sdcard/Download/patched-boot.img /tmp
}

reboot_to_bootloader() {
    adb -s "$PHONE_ADB_SERIAL_NUMBER" reboot bootloader
}

wait_for_phone_to_be_in_fastboot() {
    SECONDS=0
    until check_phone_is_in_fastboot_mode; do

        if ((SECONDS > 60)); then
            echo "Giving up..."
            exit 2
        fi

        echo "Phone is not in fastboot mode yet. Waiting..."
        sleep 5
    done
}

flash_patched_boot_image() {
    fastboot -s "$PHONE_ADB_SERIAL_NUMBER" flash boot /tmp/patched-boot.img
}

reboot_phone() {
    fastboot -s "$PHONE_ADB_SERIAL_NUMBER" reboot
}

enable_adb_root_access() {
    adb -s "$PHONE_ADB_SERIAL_NUMBER" root &&
        adb -s "$PHONE_ADB_SERIAL_NUMBER" shell ls / # Check that the phone allows root debugging.
}

main() {
    check_phone_is_connected
    enable_adb_root_access
    download_latest_lineageos_build
    extract_boot_image
    transfer_unpatched_boot_image_to_phone
    patch_boot_image_on_phone
    transfer_patched_boot_image_to_pc
    reboot_to_bootloader
    wait_for_phone_to_be_in_fastboot
    flash_patched_boot_image
    reboot_phone
}

# Run the main only when this file is executed as script, to help with testing.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
